swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /director:
    get:
      operationId: directors.read_all
      tags:
        - Directors
      summary: Read the entire set of director
      description: Read the entire set of director
      parameters:
        - name: id
          in: query
          description: ID of the Director to get
          type: integer
          required: False
        - name: sort_by
          in: query
          description: Sort data Director by id, name, department, gender, uid
          type: string
          required: False
        - name: reverse
          in: query
          description: Reverse sort for Director
          type: boolean
          required: False
        - name: movie
          in: query
          description: Format return movie data, half or full. 
          type: string
          required: False
        - name: limit
          in: query
          description: Limit for return Director data. 
          type: integer
          required: False
        - name: movie_sort
          in: query
          description: Sort movie data. Sort by id, budget, original_title, overview, popularity, release_date, revenue, tagline, title, uid and vote_average if movie is full. Sort by id, release_date, title and vote_average if movie is half
          type: string
          required: False
        - name: movie_sort_reverse
          in: query
          description: Reverse sort for movie
          type: boolean
          required: False
        - name: movie_limit
          in: query
          description: Limit of movie data. 
          type: integer
          required: False
      responses:
        200:
          description: Successfully read director set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: Id of the director
                name:
                  type: string
                  description: Name of the director
                gender:
                  type: integer
                  description: Gender of the director. 1 is Female, 2 is Male, 0 is Null
                uid:
                  type: integer
                  description: User ID of the director, uniq
                department:
                  type: string
                  description: Department of the director

    post:
      operationId: directors.create
      tags:
        - Directors
      summary: Create a director
      description: Create a new director
      parameters:
        - name: director
          in: body
          description: Director to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director. 1 is Female, 2 is Male, 0 is Null
              uid:
                type: integer
                description: User ID of the director, uniq
              department:
                type: string
                description: Department of the director
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              id:
                type: integer
                description: Id of the director
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director. 1 is Female, 2 is Male, 0 is Null
              uid:
                type: integer
                description: User ID of the director, uniq
              department:
                type: string
                description: Department of the director

  /director/{director_id}:
    get:
      operationId: directors.read_one
      tags:
        - Directors
      summary: Search a director by ID
      description: Search a director by ID
      parameters:
        - name: director_id
          in: path
          description: ID of the Director to get
          type: integer
          required: True
        - name: movie
          in: query
          description: Format return movie data, half or full. 
          type: string
          required: False
      responses:
        200:
          description: Successfully read director set operation
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Id of the director
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director. 1 is Female, 2 is Male, 0 is Null
              uid:
                type: integer
                description: User ID of the director, uniq
              department:
                type: string
                description: Department of the director

    put:
      operationId: directors.update
      tags:
        - Directors
      summary: Update a director
      description: Update a director
      parameters:
        - name: director_id
          in: path
          description: ID of the Director to update
          type: integer
          required: True
        - name: director
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director. 1 is Female, 2 is Male, 0 is Null
              uid:
                type: integer
                description: User ID of the director, uniq
              department:
                type: string
                description: Department of the director
      responses:
        200:
          description: Successfully read director set operation
          schema:
            properties:
              id:
                type: integer
                description: Id of the director
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director. 1 is Female, 2 is Male, 0 is Null
              uid:
                type: integer
                description: User ID of the director, uniq
              department:
                type: string
                description: Department of the director
      
    delete:
      operationId: directors.delete
      tags:
        - Directors
      summary: Delete a director
      description: Delete a director
      parameters:
        - name: director_id
          in: path
          description: id of the Director to delete
          type: integer
          required: True
      responses:
        200:
          description: Successfully delete a Director

  #########################################################################################
  #########################################################################################
  #########################################################################################
  
  /movie:
    get:
      operationId: movies.read_all
      tags:
        - Movies
      summary: Read the entire set of movie, sorted by ID
      description: Read the entire set of movie, sorted by ID
      parameters:
        - name: sort_by
          in: query
          description: Sort movie data. Sort by id, budget, original_title, overview, popularity, release_date, revenue, tagline, title, uid and vote_average
          type: string
          required: False
        - name: reverse
          in: query
          description: Reverse sort for Movie
          type: boolean
          required: False
        - name: limit
          in: query
          description: Limit of Movie Data
          type: integer
          required: False
        - name: director
          in: query
          description: Format return director data, half or full. 
          type: string
          required: False
        
      responses:
        200:
          description: Successfully read movie set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: Id of the movie
                original_title:
                  type: string
                  description: Original title of the movie
                budget:
                  type: integer
                  description: Budget of the movie
                popularity:
                  type: integer
                  description: Popularity of the movie
                release_date:
                  type: string
                  description: Release Date of the movie
                revenue:
                  type: integer
                  description: Revenue of the movie
                title:
                  type: string
                  description: Title of the movie
                vote_average:
                  type: number
                  description: Vote average of the movie
                vote_count:
                  type: integer
                  description: Vote count of the movie
                overview:
                  type: string
                  description: Overview of the movie
                tagline:
                  type: string
                  description: tagline of the movie
                uid:
                  type: integer
                  description: User ID of the movie
                directors:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Director ID of the movie
                    name:
                      type: string
                      description: Name of Director of the movie
    
  /director/{director_id}/movie:
    post:
      operationId: movies.create
      tags:
        - Movies
      summary: Create a movie
      description: Create a new movie
      parameters:
        - name: director_id
          in: path
          description: ID of the Director to get
          type: integer
          required: True
        - name: movie
          in: body
          description: Movie to create
          required: True
          schema:
            type: object
            properties:
              original_title:
                type: string
                description: Original title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release Date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: tagline of the movie
              uid:
                type: integer
                description: User ID of the movie
              director_id:
                type: integer
                description: Director ID of the movie
      responses:
        201:
          description: Successfully created movie
          schema:
            properties:
              id:
                type: integer
                description: Id of the movie
              original_title:
                type: string
                description: Original title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release Date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: tagline of the movie
              uid:
                type: integer
                description: User ID of the movie
              director_id:
                type: integer
                description: Director ID of the movie
              director_name:
                type: string
                description: Name of Director of the movie

  /director/{director_id}/movie/{movie_id}:
    get:
      operationId: movies.read_one
      tags:
        - Movies
      summary: Search a movie by ID
      description: Search a movie by ID
      parameters:
        - name: director_id
          in: path
          description: ID of the Director to get
          type: integer
          required: True
        - name: movie_id
          in: path
          description: ID of the Movie to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read director set operation
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Id of the movie
              original_title:
                type: string
                description: Original title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release Date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: tagline of the movie
              uid:
                type: integer
                description: User ID of the movie
              director_id:
                type: integer
                description: Director ID of the movie
              director_name:
                type: string
                description: Name of Director of the movie

    put:
      operationId: movies.update
      tags:
        - Movies
      summary: Update a movie
      description: Update a movie
      parameters:
        - name: director_id
          in: path
          description: ID of the Director to get
          type: integer
          required: True
        - name: movie_id
          in: path
          description: ID of the Movie to get
          type: integer
          required: True
        - name: movie
          in: body
          schema:
            type: object
            properties:
              original_title:
                type: string
                description: Original title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release Date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: tagline of the movie
              uid:
                type: integer
                description: User ID of the movie
              director_id:
                type: integer
                description: Director ID of the movie
      responses:
        200:
          description: Successfully read movie set operation
          schema:
            properties:
              id:
                type: integer
                description: Id of the movie
              original_title:
                type: string
                description: Original title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release Date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: tagline of the movie
              uid:
                type: integer
                description: User ID of the movie
              director_id:
                type: integer
                description: Director ID of the movie
              director_name:
                type: string
                description: Name of Director of the movie
      
    delete:
      operationId: movies.delete
      tags:
        - Movies
      summary: Delete a movie
      description: Delete a movie
      parameters:
        - name: director_id
          in: path
          description: ID of the Director to get
          type: integer
          required: True
        - name: movie_id
          in: path
          description: ID of the movie to delete
          type: integer
          required: True
      responses:
        200:
          description: Successfully delete a Movie

